insert ignore into Author (ID, name, nationality, birth_year) values (1, "Cornie Nabarro", "Portugal", 1993);
insert ignore into Author (ID, name, nationality, birth_year) values (2, "Cassius Aaron", "China", 1910);
insert ignore into Author (ID, name, nationality, birth_year) values (3, "Christye Blondell", "Ethiopia", 1878);
insert ignore into Author (ID, name, nationality, birth_year) values (4, "Ginelle Hoogendorp", "United States", 1930);
insert ignore into Author (ID, name, nationality, birth_year) values (5, "Henri Brettoner", "Portugal", 1988);
insert ignore into Author (ID, name, nationality, birth_year) values (6, "Georgine Houseago", "North Korea", 1895);
insert ignore into Author (ID, name, nationality, birth_year) values (7, "Layton Peery", "Indonesia", 1943);
insert ignore into Author (ID, name, nationality, birth_year) values (8, "Karoly Sparrow", "China", 1903);
insert ignore into Author (ID, name, nationality, birth_year) values (9, "Wallie Densie", "Thailand", 1967);
insert ignore into Author (ID, name, nationality, birth_year) values (10, "Florance Le Teve", "Japan", 1848);
insert ignore into Author (ID, name, nationality, birth_year) values (11, "Sherri Haller", "China", 1928);
insert ignore into Author (ID, name, nationality, birth_year) values (12, "Boyd Meekings", "Brazil", 2003);
insert ignore into Author (ID, name, nationality, birth_year) values (13, "Klement Pryor", "Chile", 1908);
insert ignore into Author (ID, name, nationality, birth_year) values (14, "Kristina Pengilly", "Netherlands", 1935);
insert ignore into Author (ID, name, nationality, birth_year) values (15, "Ferdie Culbard", "France", 1904);
insert ignore into Author (ID, name, nationality, birth_year) values (16, "Lucita Lamputt", "Czech Republic", 1869);
insert ignore into Author (ID, name, nationality, birth_year) values (17, "Franklin Signe", "Indonesia", 1836);
insert ignore into Author (ID, name, nationality, birth_year) values (18, "Marguerite Thornthwaite", "Argentina", 1842);
insert ignore into Author (ID, name, nationality, birth_year) values (19, "Marguerite Bercher", "East Timor", 1992);
insert ignore into Author (ID, name, nationality, birth_year) values (20, "Shaun Greasty", "Croatia", 1903);
insert ignore into Author (ID, name, nationality, birth_year) values (21, "Cathi Manna", "Portugal", 1964);
insert ignore into Author (ID, name, nationality, birth_year) values (22, "Trudie Potebury", "Republic of the Congo", 1969);
insert ignore into Author (ID, name, nationality, birth_year) values (23, "Hailey Crewes", "Bangladesh", 1823);
insert ignore into Author (ID, name, nationality, birth_year) values (24, "Tonye Danilovitch", "Ukraine", 1843);
insert ignore into Author (ID, name, nationality, birth_year) values (25, "Tillie Minkin", "Poland", 1989);
insert ignore into Author (ID, name, nationality, birth_year) values (26, "Denny Laight", "South Africa", 2005);
insert ignore into Author (ID, name, nationality, birth_year) values (27, "Sumner Champneys", "Russia", 1914);
insert ignore into Author (ID, name, nationality, birth_year) values (28, "Nikki Kondrat", "Iran", 1812);
insert ignore into Author (ID, name, nationality, birth_year) values (29, "Ignatius Heskins", "China", 1899);
insert ignore into Author (ID, name, nationality, birth_year) values (30, "Buckie Straffon", "Indonesia", 1993);
