insert ignore into Tag (name) values ('Fantasy');
insert ignore into Tag (name) values ('Adventure');
insert ignore into Tag (name) values ('Romance');
insert ignore into Tag (name) values ('Contemporary');
insert ignore into Tag (name) values ('Dystopian');
insert ignore into Tag (name) values ('Mystery');
insert ignore into Tag (name) values ('Horror');
insert ignore into Tag (name) values ('Thriller');
insert ignore into Tag (name) values ('Paranormal');
insert ignore into Tag (name) values ('Historical fiction');
insert ignore into Tag (name) values ('Science Fiction');
insert ignore into Tag (name) values ('Children');
insert ignore into Tag (name) values ('Memoir');
insert ignore into Tag (name) values ('Cookbook');
insert ignore into Tag (name) values ('Art');
insert ignore into Tag (name) values ('Self-help');
insert ignore into Tag (name) values ('Development');
insert ignore into Tag (name) values ('Motivational');
insert ignore into Tag (name) values ('Health');
insert ignore into Tag (name) values ('History');
insert ignore into Tag (name) values ('Travel');
insert ignore into Tag (name) values ('Families & Relationships');
insert ignore into Tag (name) values ('Humor');
