insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 1, 101, "8:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 1, 101, "10:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 1, 102, "8:30", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 1, 102, "8:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 1, 103, "9:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 1, 103, "9:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 1, 104, "9:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 1, 104, "8:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 1, 105, "10:00", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 1, 105, "8:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 2, 201, "10:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 2, 201, "9:30", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 2, 202, "9:30", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 2, 202, "8:30", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 2, 203, "8:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 2, 203, "8:30", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 2, 204, "10:00", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 2, 204, "9:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 2, 205, "9:30", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 2, 205, "8:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 3, 301, "9:30", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 3, 301, "9:00", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 3, 302, "9:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 3, 302, "9:00", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 3, 303, "10:00", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 3, 303, "9:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 3, 304, "8:00", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 3, 304, "9:30", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 3, 305, "10:00", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 3, 305, "8:30", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 4, 401, "9:30", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 4, 401, "10:00", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 4, 402, "10:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 4, 402, "9:30", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 4, 403, "9:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 4, 403, "9:30", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 4, 404, "10:00", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 4, 404, "8:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 4, 405, "8:30", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 4, 405, "8:30", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 5, 501, "9:30", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 5, 501, "9:30", "17:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 5, 502, "8:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 5, 502, "8:00", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 5, 503, "9:00", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 5, 503, "10:00", "18:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 5, 504, "9:00", "19:00");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 5, 504, "8:00", "18:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "John M. Harper Branch", 5, 505, "10:00", "17:30");
insert ignore into Location (ID, building, floor, room, open_time, close_time) values (NULL, "Eastside Branch", 5, 505, "9:30", "17:30");
