insert ignore into Publisher (ID, name, address) values (1, "Abshire LLC", "786 Garrison Junction");
insert ignore into Publisher (ID, name, address) values (2, "Metz, Crist and Zemlak", "135 Bobwhite Plaza");
insert ignore into Publisher (ID, name, address) values (3, "Conn-Romaguera", "54 Moose Pass");
insert ignore into Publisher (ID, name, address) values (4, "Hessel Inc", "2689 Hoepker Point");
insert ignore into Publisher (ID, name, address) values (5, "Kautzer LLC", "39085 Anthes Drive");
insert ignore into Publisher (ID, name, address) values (6, "Huel-Frami", "84 Russell Terrace");
insert ignore into Publisher (ID, name, address) values (7, "Huel-Frami", "6 Ohio Plaza");
insert ignore into Publisher (ID, name, address) values (8, "Bradtke, Hansen and Goldner", "9101 Pleasure Lane");
insert ignore into Publisher (ID, name, address) values (9, "Gibson, Langworth and McDermott", "84 Russell Terrace");
insert ignore into Publisher (ID, name, address) values (10, "Hettinger-Rutherford", "57 Sherman Center");
