insert into Publisher (ID, name, address) values (1, 'Joeann Abrahamsohn', '7 Darwin Park');
insert into Publisher (ID, name, address) values (2, 'Lorettalorna Brunnstein', '32 Bayside Court');
insert into Publisher (ID, name, address) values (3, 'Martie Giorgiutti', '8 Mesta Way');
insert into Publisher (ID, name, address) values (4, 'Lennie Hospital', '7 Melvin Way');
insert into Publisher (ID, name, address) values (5, 'Coriss Slocom', '07156 Clove Drive');
insert into Publisher (ID, name, address) values (6, 'Lena Greasley', '02 Rieder Drive');
insert into Publisher (ID, name, address) values (7, 'Paddie Battram', '0 Forster Circle');
insert into Publisher (ID, name, address) values (8, 'Linnea Craggs', '642 Crowley Hill');
insert into Publisher (ID, name, address) values (9, 'Rickert Bazeley', '3 Prairieview Lane');
insert into Publisher (ID, name, address) values (10, 'Olenka O''Duane', '1 Stang Drive');
insert into Publisher (ID, name, address) values (11, 'Prinz Fuster', '43899 Rutledge Plaza');
insert into Publisher (ID, name, address) values (12, 'Scarlett Egentan', '2022 Utah Avenue');
insert into Publisher (ID, name, address) values (13, 'Zulema Longworth', '89074 Thompson Center');
insert into Publisher (ID, name, address) values (14, 'Sharai Creeboe', '77 Miller Lane');
insert into Publisher (ID, name, address) values (15, 'Greta Courtman', null);
insert into Publisher (ID, name, address) values (16, 'Elbert Grimestone', '705 Lyons Lane');
insert into Publisher (ID, name, address) values (17, 'Francyne Antonio', '05 Oak Lane');
insert into Publisher (ID, name, address) values (18, 'Tadeas Conneau', '815 Welch Way');
insert into Publisher (ID, name, address) values (19, 'Claudia Mainston', '6332 Nelson Circle');
insert into Publisher (ID, name, address) values (20, 'Wallis Bewlie', '0423 Johnson Hill');
insert into Publisher (ID, name, address) values (21, 'Lois Paxton', null);
insert into Publisher (ID, name, address) values (22, 'Bryan Oswal', '21188 Fordem Way');
insert into Publisher (ID, name, address) values (23, 'Ruthy Sheldrick', '6 Kennedy Road');
insert into Publisher (ID, name, address) values (24, 'Minta Commucci', '7317 Sutherland Center');
insert into Publisher (ID, name, address) values (25, 'Rockie MacKain', '08834 Fairfield Alley');
insert into Publisher (ID, name, address) values (26, 'Tynan Leathlay', null);
insert into Publisher (ID, name, address) values (27, 'Courtney Sheward', '14447 Hauk Parkway');
insert into Publisher (ID, name, address) values (28, 'Brandie Wraight', '63 Village Green Trail');
insert into Publisher (ID, name, address) values (29, 'Katerine Heavy', '9 Petterle Road');
insert into Publisher (ID, name, address) values (30, 'Evangelin Zouch', '764 Cardinal Avenue');
insert into Publisher (ID, name, address) values (31, 'Nataniel Raselles', '8652 Springview Street');
insert into Publisher (ID, name, address) values (32, 'Rowe Soigne', '7232 Bunker Hill Junction');
insert into Publisher (ID, name, address) values (33, 'Briney Keele', '7 Shelley Terrace');
insert into Publisher (ID, name, address) values (34, 'Clarita Halle', '2525 Bultman Avenue');
insert into Publisher (ID, name, address) values (35, 'Early Rampton', '7104 Cardinal Plaza');
insert into Publisher (ID, name, address) values (36, 'Keriann Meachan', '58 Holmberg Pass');
insert into Publisher (ID, name, address) values (37, 'Vivia Tash', '4 Vernon Place');
insert into Publisher (ID, name, address) values (38, 'Silvana Nucator', '0 Sauthoff Drive');
insert into Publisher (ID, name, address) values (39, 'Gabrila Wesson', '884 Mcbride Way');
insert into Publisher (ID, name, address) values (40, 'Anselma Spurr', null);
insert into Publisher (ID, name, address) values (41, 'Fidel Haddock', '859 Lukken Trail');
insert into Publisher (ID, name, address) values (42, 'Sheffy Wraxall', '5510 Grayhawk Alley');
insert into Publisher (ID, name, address) values (43, 'Consuela Ivie', '670 Rusk Point');
insert into Publisher (ID, name, address) values (44, 'Hadrian McFadin', '62416 Schiller Way');
insert into Publisher (ID, name, address) values (45, 'Courtney Radden', '263 Oakridge Way');
insert into Publisher (ID, name, address) values (46, 'Sancho Skegg', '1659 Debs Junction');
insert into Publisher (ID, name, address) values (47, 'Benedicta Onthank', '157 Forest Dale Drive');
insert into Publisher (ID, name, address) values (48, 'Marty Acom', '705 Elmside Place');
insert into Publisher (ID, name, address) values (49, 'Carine Masters', '3 Waywood Point');
insert into Publisher (ID, name, address) values (50, 'Woodie Dawby', '1827 Lakewood Place');
