insert into Publisher (ID, name, address) values (1, "Windler, Ward and Bruen", "11 Bluejay Center");
insert into Publisher (ID, name, address) values (2, "Schaefer, Wuckert and Kihn", "378 Kings Hill");
insert into Publisher (ID, name, address) values (3, "Zulauf Inc", "378 Kings Hill");
insert into Publisher (ID, name, address) values (4, "Grant-Romaguera", "11776 Arrowood Trail");
insert into Publisher (ID, name, address) values (5, "Hauck LLC", "66 Upham Lane");
insert into Publisher (ID, name, address) values (6, "Robel Group", "6 Pankratz Hill");
insert into Publisher (ID, name, address) values (7, "Gaylord, Mohr and Hegmann", "1933 Green Road");
insert into Publisher (ID, name, address) values (8, "Davis Group", "6 Pankratz Hill");
insert into Publisher (ID, name, address) values (9, "Rau, Block and O'Conner", "87171 Katie Lane");
insert into Publisher (ID, name, address) values (10, "West-Kuhic", "40847 Macpherson Way");
insert into Publisher (ID, name, address) values (11, "Rodriguez LLC", "56 Troy Parkway");
insert into Publisher (ID, name, address) values (12, "Hessel Inc", "3764 Toban Terrace");
insert into Publisher (ID, name, address) values (13, "Corkery, Larson and Cassin", "818 Ryan Lane");
insert into Publisher (ID, name, address) values (14, "Stiedemann Group", "3977 Stang Pass");
insert into Publisher (ID, name, address) values (15, "O'Keefe LLC", "451 Northfield Parkway");
insert into Publisher (ID, name, address) values (16, "Marquardt, Harris and Macejkovic", "6137 Meadow Vale Crossing");
insert into Publisher (ID, name, address) values (17, "Herzog Group", "3124 Bluestem Plaza");
insert into Publisher (ID, name, address) values (18, "Schiller, Cummerata and Heidenreich", "4 Dryden Crossing");
insert into Publisher (ID, name, address) values (19, "Cummerata LLC", "94 Division Crossing");
insert into Publisher (ID, name, address) values (20, "Jacobs Group", "40847 Macpherson Way");
insert into Publisher (ID, name, address) values (21, "Bashirian LLC", "2 Straubel Circle");
insert into Publisher (ID, name, address) values (22, "Mohr LLC", "50 Eagan Terrace");
insert into Publisher (ID, name, address) values (23, "Cummerata LLC", "018 Fulton Alley");
insert into Publisher (ID, name, address) values (24, "Vandervort LLC", "74 Hovde Hill");
insert into Publisher (ID, name, address) values (25, "Satterfield, Kub and Stokes", "8 Bellgrove Lane");
insert into Publisher (ID, name, address) values (26, "Barrows Group", "6 Ohio Plaza");
insert into Publisher (ID, name, address) values (27, "Vandervort LLC", "980 Lerdahl Drive");
insert into Publisher (ID, name, address) values (28, "Cronin LLC", "6 Forster Alley");
insert into Publisher (ID, name, address) values (29, "Quitzon-Kuhn", "788 Coolidge Place");
insert into Publisher (ID, name, address) values (30, "Kuhlman-Emmerich", "5874 Almo Alley");
insert into Publisher (ID, name, address) values (31, "Ledner-Kassulke", "84 Tony Terrace");
insert into Publisher (ID, name, address) values (32, "Roob LLC", "133 Pine View Circle");
insert into Publisher (ID, name, address) values (33, "Kuhn, Kemmer and Skiles", "8522 Park Meadow Drive");
insert into Publisher (ID, name, address) values (34, "Kunze LLC", "5874 Almo Alley");
insert into Publisher (ID, name, address) values (35, "Altenwerth, Glover and Pagac", "5795 Westport Parkway");
insert into Publisher (ID, name, address) values (36, "Bosco LLC", "9 Michigan Court");
insert into Publisher (ID, name, address) values (37, "Rath Group", "94 Dovetail Park");
insert into Publisher (ID, name, address) values (38, "Funk and Sons", "20 Hazelcrest Circle");
insert into Publisher (ID, name, address) values (39, "Blick, Haley and Rohan", "0625 Spaight Drive");
insert into Publisher (ID, name, address) values (40, "Blick, Haley and Rohan", "5336 Rockefeller Road");
insert into Publisher (ID, name, address) values (41, "Gaylord, Mohr and Hegmann", "8 Moland Point");
insert into Publisher (ID, name, address) values (42, "Pacocha, Nader and Ullrich", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (43, "Hettinger-Gaylord", "3 Hoepker Street");
insert into Publisher (ID, name, address) values (44, "Braun and Sons", "7344 Golf View Pass");
insert into Publisher (ID, name, address) values (45, "Hirthe, Towne and Moore", "9 Northport Junction");
insert into Publisher (ID, name, address) values (46, "Bogan, Auer and Crooks", "869 Mayer Park");
insert into Publisher (ID, name, address) values (47, "Klein Inc", "6709 Melvin Alley");
insert into Publisher (ID, name, address) values (48, "Bartell-Quigley", "5874 Almo Alley");
insert into Publisher (ID, name, address) values (49, "Emmerich, Kilback and Bednar", "496 Texas Junction");
insert into Publisher (ID, name, address) values (50, "Vandervort LLC", "216 Spenser Point");
insert into Publisher (ID, name, address) values (51, "Hudson-Mosciski", "242 Debra Crossing");
insert into Publisher (ID, name, address) values (52, "Weber, Wintheiser and Homenick", "05186 Donald Terrace");
insert into Publisher (ID, name, address) values (53, "Heidenreich, Shanahan and Tromp", "54 Moose Pass");
insert into Publisher (ID, name, address) values (54, "Labadie-Wisoky", "9 Michigan Court");
insert into Publisher (ID, name, address) values (55, "Schumm-Murazik", "6 Stephen Pass");
insert into Publisher (ID, name, address) values (56, "Stoltenberg, Tremblay and Hagenes", "09 Thierer Drive");
insert into Publisher (ID, name, address) values (57, "Altenwerth, Glover and Pagac", "3977 Stang Pass");
insert into Publisher (ID, name, address) values (58, "Hermiston-Goodwin", "29727 Knutson Court");
insert into Publisher (ID, name, address) values (59, "Halvorson-Runolfsdottir", "323 Bartillon Alley");
insert into Publisher (ID, name, address) values (60, "Frami LLC", "333 Oxford Drive");
insert into Publisher (ID, name, address) values (61, "Gutkowski, Nikolaus and Keebler", "6137 Meadow Vale Crossing");
insert into Publisher (ID, name, address) values (62, "Deckow, Skiles and Terry", "873 Delaware Point");
insert into Publisher (ID, name, address) values (63, "Hayes Inc", "48 Chinook Circle");
insert into Publisher (ID, name, address) values (64, "Hessel LLC", "4 Mockingbird Park");
insert into Publisher (ID, name, address) values (65, "Stoltenberg, D'Amore and Gutkowski", "87041 Dakota Center");
insert into Publisher (ID, name, address) values (66, "Rath Group", "7 Troy Parkway");
insert into Publisher (ID, name, address) values (67, "Spinka-Waelchi", "115 Towne Street");
insert into Publisher (ID, name, address) values (68, "Friesen-Rempel", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (69, "Rice-Heathcote", "9291 Gulseth Point");
insert into Publisher (ID, name, address) values (70, "Donnelly, Mosciski and Bechtelar", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (71, "Walter, McLaughlin and Bartoletti", "65320 Moose Avenue");
insert into Publisher (ID, name, address) values (72, "Graham-Brown", "7 Eagan Terrace");
insert into Publisher (ID, name, address) values (73, "Moore-Bode", "76097 Lindbergh Hill");
insert into Publisher (ID, name, address) values (74, "Hackett LLC", "57 Sherman Center");
insert into Publisher (ID, name, address) values (75, "Hauck LLC", "7344 Golf View Pass");
insert into Publisher (ID, name, address) values (76, "Kautzer LLC", "49 Buell Parkway");
insert into Publisher (ID, name, address) values (77, "Schumm-Murazik", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (78, "Carroll-Wiza", "76581 Lakeland Junction");
insert into Publisher (ID, name, address) values (79, "Turner, Lang and Koelpin", "9 Michigan Court");
insert into Publisher (ID, name, address) values (80, "Jacobson Inc", "3764 Toban Terrace");
insert into Publisher (ID, name, address) values (81, "Crona-Schimmel", "005 Alpine Court");
insert into Publisher (ID, name, address) values (82, "Schumm-Murazik", "76097 Lindbergh Hill");
insert into Publisher (ID, name, address) values (83, "Hahn-Dickens", "1423 Drewry Street");
insert into Publisher (ID, name, address) values (84, "Bashirian LLC", "7 Coleman Crossing");
insert into Publisher (ID, name, address) values (85, "Considine, Hand and Shields", "5738 Badeau Court");
insert into Publisher (ID, name, address) values (86, "Pacocha, Nader and Ullrich", "56366 Service Street");
insert into Publisher (ID, name, address) values (87, "Klein, Feeney and Smith", "3124 Bluestem Plaza");
insert into Publisher (ID, name, address) values (88, "Thiel and Sons", "3157 Mendota Way");
insert into Publisher (ID, name, address) values (89, "Mertz, Hamill and O'Connell", "5 Village Green Lane");
insert into Publisher (ID, name, address) values (90, "Harber Inc", "1730 Darwin Park");
insert into Publisher (ID, name, address) values (91, "Hackett LLC", "63 Hazelcrest Center");
insert into Publisher (ID, name, address) values (92, "Bailey-Marquardt", "37422 Oxford Lane");
insert into Publisher (ID, name, address) values (93, "West-Kuhic", "46727 Park Meadow Alley");
insert into Publisher (ID, name, address) values (94, "Blick, Haley and Rohan", "50 Eagan Terrace");
insert into Publisher (ID, name, address) values (95, "O'Keefe LLC", "06 Bellgrove Place");
insert into Publisher (ID, name, address) values (96, "Haley-Sporer", "87171 Katie Lane");
insert into Publisher (ID, name, address) values (97, "Kuhn Group", "4862 Jana Place");
insert into Publisher (ID, name, address) values (98, "Oberbrunner Inc", "4 Mockingbird Park");
insert into Publisher (ID, name, address) values (99, "Hills, Jerde and Shields", "76581 Lakeland Junction");
insert into Publisher (ID, name, address) values (100, "Brekke Group", "06 Gina Junction");
insert into Publisher (ID, name, address) values (101, "Boyle-Little", "209 Old Shore Plaza");
insert into Publisher (ID, name, address) values (102, "Vandervort LLC", "38 Portage Crossing");
insert into Publisher (ID, name, address) values (103, "Hudson-Langworth", "9 Glendale Road");
insert into Publisher (ID, name, address) values (104, "Mayert-Trantow", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (105, "Legros Inc", "8 Bellgrove Lane");
insert into Publisher (ID, name, address) values (106, "Farrell, Stiedemann and Romaguera", "9 Erie Parkway");
insert into Publisher (ID, name, address) values (107, "Metz, Crist and Zemlak", "05 Randy Park");
insert into Publisher (ID, name, address) values (108, "Bartoletti, Goldner and Murray", "6 Stephen Pass");
insert into Publisher (ID, name, address) values (109, "Rodriguez Inc", "811 Bonner Avenue");
insert into Publisher (ID, name, address) values (110, "Farrell, Stiedemann and Romaguera", "5984 Kenwood Point");
insert into Publisher (ID, name, address) values (111, "Harber Inc", "7209 Kinsman Point");
insert into Publisher (ID, name, address) values (112, "Hirthe, Towne and Moore", "53 Lindbergh Center");
insert into Publisher (ID, name, address) values (113, "Reilly LLC", "35 Jana Point");
insert into Publisher (ID, name, address) values (114, "Hauck LLC", "87171 Katie Lane");
insert into Publisher (ID, name, address) values (115, "Dare Group", "797 Moland Drive");
insert into Publisher (ID, name, address) values (116, "Prosacco-Kihn", "7 Eagan Terrace");
insert into Publisher (ID, name, address) values (117, "Cronin LLC", "05186 Donald Terrace");
insert into Publisher (ID, name, address) values (118, "Moore, Prosacco and Christiansen", "66 Claremont Pass");
insert into Publisher (ID, name, address) values (119, "Metz, Crist and Zemlak", "6 New Castle Road");
insert into Publisher (ID, name, address) values (120, "McGlynn and Sons", "9 Glendale Road");
insert into Publisher (ID, name, address) values (121, "Grant-Romaguera", "5528 Westridge Drive");
insert into Publisher (ID, name, address) values (122, "Zulauf Inc", "5738 Badeau Court");
insert into Publisher (ID, name, address) values (123, "Bradtke, Hansen and Goldner", "46727 Park Meadow Alley");
insert into Publisher (ID, name, address) values (124, "Bashirian LLC", "49 Buell Parkway");
insert into Publisher (ID, name, address) values (125, "Hudson-Mosciski", "54 Moose Pass");
insert into Publisher (ID, name, address) values (126, "Goyette, Emard and Stokes", "323 Bartillon Alley");
insert into Publisher (ID, name, address) values (127, "Cronin LLC", "06 Bellgrove Place");
insert into Publisher (ID, name, address) values (128, "Boyle-Little", "873 Delaware Point");
insert into Publisher (ID, name, address) values (129, "Hauck LLC", "873 Delaware Point");
insert into Publisher (ID, name, address) values (130, "Bartell-Quigley", "40587 Dorton Court");
insert into Publisher (ID, name, address) values (131, "Rath Group", "260 Mcguire Point");
insert into Publisher (ID, name, address) values (132, "Flatley Inc", "811 Bonner Avenue");
insert into Publisher (ID, name, address) values (133, "Gislason, Harris and Altenwerth", "26331 Judy Terrace");
insert into Publisher (ID, name, address) values (134, "Harber Inc", "5 Sommers Junction");
insert into Publisher (ID, name, address) values (135, "Spinka-Waelchi", "333 Oxford Drive");
insert into Publisher (ID, name, address) values (136, "Gaylord, Mohr and Hegmann", "9 Northport Junction");
insert into Publisher (ID, name, address) values (137, "Rau, Block and O'Conner", "44075 Green Ridge Road");
insert into Publisher (ID, name, address) values (138, "Robel Group", "9531 Dapin Trail");
insert into Publisher (ID, name, address) values (139, "Windler, Ward and Bruen", "7 Eagan Terrace");
insert into Publisher (ID, name, address) values (140, "Moore-Bode", "09 Thierer Drive");
insert into Publisher (ID, name, address) values (141, "Dare Group", "216 Spenser Point");
insert into Publisher (ID, name, address) values (142, "Kuhlman-Emmerich", "323 Bartillon Alley");
insert into Publisher (ID, name, address) values (143, "Ruecker LLC", "06 Bellgrove Place");
insert into Publisher (ID, name, address) values (144, "Hills, Jerde and Shields", "5 Village Green Lane");
insert into Publisher (ID, name, address) values (145, "Gutkowski, Kunde and Purdy", "8 Moland Point");
insert into Publisher (ID, name, address) values (146, "Mayert-Trantow", "47323 Anthes Pass");
insert into Publisher (ID, name, address) values (147, "Bahringer, Fay and Skiles", "5984 Kenwood Point");
insert into Publisher (ID, name, address) values (148, "Friesen-Rempel", "3 Hoepker Street");
insert into Publisher (ID, name, address) values (149, "Emmerich, Kilback and Bednar", "9518 Myrtle Terrace");
insert into Publisher (ID, name, address) values (150, "Oberbrunner Inc", "9 Erie Parkway");
insert into Publisher (ID, name, address) values (151, "Heidenreich, Shanahan and Tromp", "7209 Kinsman Point");
insert into Publisher (ID, name, address) values (152, "Graham-Brown", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (153, "Conn-Romaguera", "375 Hooker Park");
insert into Publisher (ID, name, address) values (154, "Heller Group", "3417 Vidon Point");
insert into Publisher (ID, name, address) values (155, "Osinski, Schumm and Jacobson", "5336 Rockefeller Road");
insert into Publisher (ID, name, address) values (156, "Windler, Ward and Bruen", "5985 Monterey Place");
insert into Publisher (ID, name, address) values (157, "Strosin-Collins", "6 Pankratz Hill");
insert into Publisher (ID, name, address) values (158, "Conn LLC", "284 Straubel Junction");
insert into Publisher (ID, name, address) values (159, "Pacocha, Nader and Ullrich", "09189 Elgar Place");
insert into Publisher (ID, name, address) values (160, "Spinka and Sons", "5172 Coolidge Center");
insert into Publisher (ID, name, address) values (161, "Prosacco-Boyle", "9 Glendale Road");
insert into Publisher (ID, name, address) values (162, "Turner, Lang and Koelpin", "7 Bunker Hill Road");
insert into Publisher (ID, name, address) values (163, "Donnelly, Mosciski and Bechtelar", "3157 Mendota Way");
insert into Publisher (ID, name, address) values (164, "O'Keefe-Hintz", "973 Ridge Oak Hill");
insert into Publisher (ID, name, address) values (165, "Davis Group", "8 Del Sol Trail");
insert into Publisher (ID, name, address) values (166, "Ritchie, Pouros and Botsford", "76581 Lakeland Junction");
insert into Publisher (ID, name, address) values (167, "Hessel Inc", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (168, "Vandervort LLC", "53 Lindbergh Center");
insert into Publisher (ID, name, address) values (169, "Reynolds-Nicolas", "018 Fulton Alley");
insert into Publisher (ID, name, address) values (170, "Donnelly, Mosciski and Bechtelar", "323 Bartillon Alley");
insert into Publisher (ID, name, address) values (171, "Bartell-Quigley", "9531 Dapin Trail");
insert into Publisher (ID, name, address) values (172, "Predovic, Schaefer and Reinger", "9 Glendale Road");
insert into Publisher (ID, name, address) values (173, "Spinka-Waelchi", "66 Claremont Pass");
insert into Publisher (ID, name, address) values (174, "Harber Inc", "157 Helena Avenue");
insert into Publisher (ID, name, address) values (175, "Lang Inc", "43 Meadow Vale Park");
insert into Publisher (ID, name, address) values (176, "Brekke Group", "09189 Elgar Place");
insert into Publisher (ID, name, address) values (177, "Flatley-Cummerata", "57 Sherman Center");
insert into Publisher (ID, name, address) values (178, "Rice-Heathcote", "9518 Myrtle Terrace");
insert into Publisher (ID, name, address) values (179, "Considine-Dare", "133 Pine View Circle");
insert into Publisher (ID, name, address) values (180, "Mayert-Trantow", "3764 Toban Terrace");
insert into Publisher (ID, name, address) values (181, "Oberbrunner, Kessler and Gorczany", "08 Division Pass");
insert into Publisher (ID, name, address) values (182, "Hackett LLC", "46 Emmet Center");
insert into Publisher (ID, name, address) values (183, "Legros Inc", "5 Village Green Lane");
insert into Publisher (ID, name, address) values (184, "Blick, Haley and Rohan", "3764 Toban Terrace");
insert into Publisher (ID, name, address) values (185, "Howe-Gusikowski", "49 Buell Parkway");
insert into Publisher (ID, name, address) values (186, "Schumm-Murazik", "40587 Dorton Court");
insert into Publisher (ID, name, address) values (187, "Gutkowski, Kunde and Purdy", "1 Welch Drive");
insert into Publisher (ID, name, address) values (188, "Heller Group", "47 Mitchell Pass");
insert into Publisher (ID, name, address) values (189, "Brekke Group", "43 Meadow Vale Park");
insert into Publisher (ID, name, address) values (190, "Howe-Gusikowski", "242 Debra Crossing");
insert into Publisher (ID, name, address) values (191, "Bradtke, Hansen and Goldner", "66 Claremont Pass");
insert into Publisher (ID, name, address) values (192, "Predovic, Schaefer and Reinger", "9 Alpine Street");
insert into Publisher (ID, name, address) values (193, "Bogan, Auer and Crooks", "5 Sommers Junction");
insert into Publisher (ID, name, address) values (194, "Watsica, Wisozk and Wolff", "35 Muir Circle");
insert into Publisher (ID, name, address) values (195, "Ziemann-Moen", "8 Del Sol Trail");
insert into Publisher (ID, name, address) values (196, "Ledner-Kassulke", "5985 Monterey Place");
insert into Publisher (ID, name, address) values (197, "Lindgren and Sons", "645 Meadow Valley Point");
insert into Publisher (ID, name, address) values (198, "Haley-Sporer", "9 Alpine Street");
insert into Publisher (ID, name, address) values (199, "Hettinger-Rutherford", "79 Dovetail Junction");
insert into Publisher (ID, name, address) values (200, "Gutkowski, Rice and Abshire", "9 Lerdahl Point");
