insert into Publisher (ID, name, address) values (1, "Hirthe, Towne and Moore", "3417 Vidon Point");
insert into Publisher (ID, name, address) values (2, "Jacobs Group", "2 Straubel Circle");
insert into Publisher (ID, name, address) values (3, "Spinka-Waelchi", "0625 Spaight Drive");
insert into Publisher (ID, name, address) values (4, "Ruecker and Sons", "9 Michigan Court");
insert into Publisher (ID, name, address) values (5, "Cronin-Ratke", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (6, "Flatley-Weber", "11 Bluejay Center");
insert into Publisher (ID, name, address) values (7, "Prosacco-Boyle", "87171 Katie Lane");
insert into Publisher (ID, name, address) values (8, "Kautzer LLC", "135 Bobwhite Plaza");
insert into Publisher (ID, name, address) values (9, "Roberts-Lynch", "6 New Castle Road");
insert into Publisher (ID, name, address) values (10, "Grant-Romaguera", "811 Bonner Avenue");
insert into Publisher (ID, name, address) values (11, "Kunze LLC", "977 Mockingbird Plaza");
insert into Publisher (ID, name, address) values (12, "Ferry LLC", "5 Weeping Birch Avenue");
insert into Publisher (ID, name, address) values (13, "Lang Inc", "496 Texas Junction");
insert into Publisher (ID, name, address) values (14, "Satterfield, Kub and Stokes", "4 Dryden Crossing");
insert into Publisher (ID, name, address) values (15, "Gaylord, Mohr and Hegmann", "1915 Hagan Lane");
insert into Publisher (ID, name, address) values (16, "Hermiston, Ankunding and Metz", "5 Sommers Junction");
insert into Publisher (ID, name, address) values (17, "Rempel, Daniel and Rempel", "5985 Monterey Place");
insert into Publisher (ID, name, address) values (18, "Nolan, Trantow and Donnelly", "0625 Spaight Drive");
insert into Publisher (ID, name, address) values (19, "Hayes and Sons", "29727 Knutson Court");
insert into Publisher (ID, name, address) values (20, "Monahan-Collins", "209 Old Shore Plaza");
insert into Publisher (ID, name, address) values (21, "Flatley Inc", "375 Hooker Park");
insert into Publisher (ID, name, address) values (22, "Connelly Group", "4688 Brentwood Parkway");
insert into Publisher (ID, name, address) values (23, "Price LLC", "216 Spenser Point");
insert into Publisher (ID, name, address) values (24, "Hessel LLC", "84 Tony Terrace");
insert into Publisher (ID, name, address) values (25, "Thiel and Sons", "39810 Bunting Trail");
insert into Publisher (ID, name, address) values (26, "Mertz, Hamill and O'Connell", "135 Bobwhite Plaza");
insert into Publisher (ID, name, address) values (27, "Ledner-Kassulke", "88805 Manley Junction");
insert into Publisher (ID, name, address) values (28, "Wilkinson, Wuckert and Franecki", "38 Portage Crossing");
insert into Publisher (ID, name, address) values (29, "Quitzon-Kuhn", "312 Muir Plaza");
insert into Publisher (ID, name, address) values (30, "Rodriguez Inc", "5 Cardinal Junction");
insert into Publisher (ID, name, address) values (31, "Davis Group", "87171 Katie Lane");
insert into Publisher (ID, name, address) values (32, "Volkman-Gibson", "11776 Arrowood Trail");
insert into Publisher (ID, name, address) values (33, "Crona-Schimmel", "50 Eagan Terrace");
insert into Publisher (ID, name, address) values (34, "Crooks LLC", "66 Upham Lane");
insert into Publisher (ID, name, address) values (35, "Glover Group", "25 Dakota Court");
insert into Publisher (ID, name, address) values (36, "Reilly LLC", "312 Muir Plaza");
insert into Publisher (ID, name, address) values (37, "Deckow, Skiles and Terry", "5172 Coolidge Center");
insert into Publisher (ID, name, address) values (38, "Bartell-Quigley", "977 Mockingbird Plaza");
insert into Publisher (ID, name, address) values (39, "Roob LLC", "3157 Mendota Way");
insert into Publisher (ID, name, address) values (40, "Paucek, Von and Cummerata", "4 Mockingbird Park");
insert into Publisher (ID, name, address) values (41, "Corkery, Larson and Cassin", "5874 Almo Alley");
insert into Publisher (ID, name, address) values (42, "Bosco LLC", "47323 Anthes Pass");
insert into Publisher (ID, name, address) values (43, "Watsica, Wisozk and Wolff", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (44, "Hermiston, Ankunding and Metz", "66 Upham Lane");
insert into Publisher (ID, name, address) values (45, "Watsica, Wisozk and Wolff", "5 Cardinal Junction");
insert into Publisher (ID, name, address) values (46, "Graham-Brown", "68 Dapin Circle");
insert into Publisher (ID, name, address) values (47, "Gaylord, Mohr and Hegmann", "640 Parkside Trail");
insert into Publisher (ID, name, address) values (48, "Maggio-Auer", "9 Calypso Plaza");
insert into Publisher (ID, name, address) values (49, "Hilpert-Kovacek", "326 Golden Leaf Drive");
insert into Publisher (ID, name, address) values (50, "Windler, Ward and Bruen", "05 Randy Park");
insert into Publisher (ID, name, address) values (51, "Hilpert-Kovacek", "8522 Park Meadow Drive");
insert into Publisher (ID, name, address) values (52, "Mayert-Trantow", "84 Russell Terrace");
insert into Publisher (ID, name, address) values (53, "Hahn-Dickens", "54 Loomis Plaza");
insert into Publisher (ID, name, address) values (54, "Metz, Crist and Zemlak", "1730 Darwin Park");
insert into Publisher (ID, name, address) values (55, "Steuber LLC", "21578 Express Alley");
insert into Publisher (ID, name, address) values (56, "Abshire LLC", "9101 Pleasure Lane");
insert into Publisher (ID, name, address) values (57, "Abshire, Kris and Tremblay", "7209 Kinsman Point");
insert into Publisher (ID, name, address) values (58, "Quitzon-Kuhn", "5984 Kenwood Point");
insert into Publisher (ID, name, address) values (59, "Rau, Block and O'Conner", "88805 Manley Junction");
insert into Publisher (ID, name, address) values (60, "Oberbrunner Inc", "898 Scoville Crossing");
insert into Publisher (ID, name, address) values (61, "Howe-Gusikowski", "5 Village Green Lane");
insert into Publisher (ID, name, address) values (62, "DuBuque LLC", "645 Meadow Valley Point");
insert into Publisher (ID, name, address) values (63, "Barrows Group", "7 Bunker Hill Road");
insert into Publisher (ID, name, address) values (64, "Purdy-Huels", "17 Nancy Park");
insert into Publisher (ID, name, address) values (65, "Donnelly, Mosciski and Bechtelar", "4 Tennessee Road");
insert into Publisher (ID, name, address) values (66, "Gislason, Harris and Altenwerth", "9 Glendale Road");
insert into Publisher (ID, name, address) values (67, "Oberbrunner, Kessler and Gorczany", "134 Alpine Circle");
insert into Publisher (ID, name, address) values (68, "Hane-Metz", "2 Straubel Circle");
insert into Publisher (ID, name, address) values (69, "Hayes Group", "33820 Charing Cross Terrace");
insert into Publisher (ID, name, address) values (70, "Ziemann-Moen", "76831 Schiller Plaza");
insert into Publisher (ID, name, address) values (71, "Hayes Group", "9 Erie Parkway");
insert into Publisher (ID, name, address) values (72, "Altenwerth-Wuckert", "9 Northport Junction");
insert into Publisher (ID, name, address) values (73, "Gutkowski, Kunde and Purdy", "18 Dwight Pass");
insert into Publisher (ID, name, address) values (74, "Purdy-Huels", "09189 Elgar Place");
insert into Publisher (ID, name, address) values (75, "Roberts-Lynch", "43 Meadow Vale Park");
insert into Publisher (ID, name, address) values (76, "Wilkinson, Wuckert and Franecki", "5172 Coolidge Center");
insert into Publisher (ID, name, address) values (77, "Hackett LLC", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (78, "Ruecker LLC", "645 Meadow Valley Point");
insert into Publisher (ID, name, address) values (79, "Renner, Dach and Rowe", "496 Texas Junction");
insert into Publisher (ID, name, address) values (80, "Bahringer, Fay and Skiles", "9 Moland Park");
insert into Publisher (ID, name, address) values (81, "Strosin-Collins", "6677 Logan Parkway");
insert into Publisher (ID, name, address) values (82, "Beier-Braun", "8 Bellgrove Lane");
insert into Publisher (ID, name, address) values (83, "Johns-Koss", "4 Muir Terrace");
insert into Publisher (ID, name, address) values (84, "Hilpert-Kovacek", "06 Bellgrove Place");
insert into Publisher (ID, name, address) values (85, "Hartmann LLC", "7 Coleman Crossing");
insert into Publisher (ID, name, address) values (86, "Altenwerth, Glover and Pagac", "9 Alpine Street");
insert into Publisher (ID, name, address) values (87, "Barrows Group", "50 Eagan Terrace");
insert into Publisher (ID, name, address) values (88, "Metz, Crist and Zemlak", "76831 Schiller Plaza");
insert into Publisher (ID, name, address) values (89, "Satterfield, Kub and Stokes", "5 Cardinal Junction");
insert into Publisher (ID, name, address) values (90, "Cronin-Ratke", "275 Mesta Street");
insert into Publisher (ID, name, address) values (91, "Lowe, Ebert and Rath", "2689 Hoepker Point");
insert into Publisher (ID, name, address) values (92, "Huel-Frami", "869 Mayer Park");
insert into Publisher (ID, name, address) values (93, "Nolan, Trantow and Donnelly", "32 Schmedeman Terrace");
insert into Publisher (ID, name, address) values (94, "Vandervort LLC", "7 Troy Parkway");
insert into Publisher (ID, name, address) values (95, "Stehr-Cruickshank", "43 Meadow Vale Park");
insert into Publisher (ID, name, address) values (96, "Bahringer, Fay and Skiles", "87041 Dakota Center");
insert into Publisher (ID, name, address) values (97, "Rodriguez LLC", "6 New Castle Road");
insert into Publisher (ID, name, address) values (98, "Purdy-Huels", "496 Texas Junction");
insert into Publisher (ID, name, address) values (99, "Flatley-Weber", "61030 Mallard Lane");
insert into Publisher (ID, name, address) values (100, "Rodriguez LLC", "8 Bellgrove Lane");
insert into Publisher (ID, name, address) values (101, "Kautzer LLC", "2 Straubel Circle");
insert into Publisher (ID, name, address) values (102, "Kautzer LLC", "16 Independence Way");
insert into Publisher (ID, name, address) values (103, "Toy, Grady and Collier", "48234 Memorial Road");
insert into Publisher (ID, name, address) values (104, "O'Keefe-Hintz", "47323 Anthes Pass");
insert into Publisher (ID, name, address) values (105, "Gislason, Harris and Altenwerth", "6137 Meadow Vale Crossing");
insert into Publisher (ID, name, address) values (106, "Donnelly, Mosciski and Bechtelar", "38 Portage Crossing");
insert into Publisher (ID, name, address) values (107, "Klein Inc", "9268 Beilfuss Road");
insert into Publisher (ID, name, address) values (108, "Crona-Schimmel", "5 Village Green Lane");
insert into Publisher (ID, name, address) values (109, "Stoltenberg, Tremblay and Hagenes", "56 Springview Junction");
insert into Publisher (ID, name, address) values (110, "Harber Inc", "48234 Memorial Road");
insert into Publisher (ID, name, address) values (111, "Ritchie, Pouros and Botsford", "3157 Mendota Way");
insert into Publisher (ID, name, address) values (112, "Lindgren and Sons", "76097 Lindbergh Hill");
insert into Publisher (ID, name, address) values (113, "Bogan, Auer and Crooks", "54 Moose Pass");
insert into Publisher (ID, name, address) values (114, "Ruecker LLC", "76581 Lakeland Junction");
insert into Publisher (ID, name, address) values (115, "Hartmann LLC", "275 Mesta Street");
insert into Publisher (ID, name, address) values (116, "Huel-Frami", "0544 Caliangt Lane");
insert into Publisher (ID, name, address) values (117, "Heidenreich, Shanahan and Tromp", "7 Bunker Hill Road");
insert into Publisher (ID, name, address) values (118, "Monahan-Collins", "788 Coolidge Place");
insert into Publisher (ID, name, address) values (119, "Robel Group", "9 Hazelcrest Junction");
insert into Publisher (ID, name, address) values (120, "Zulauf Inc", "797 Moland Drive");
insert into Publisher (ID, name, address) values (121, "Zulauf Inc", "32 Schmedeman Terrace");
insert into Publisher (ID, name, address) values (122, "Abshire, Kris and Tremblay", "92462 Glendale Terrace");
insert into Publisher (ID, name, address) values (123, "Cronin-Ratke", "5172 Coolidge Center");
insert into Publisher (ID, name, address) values (124, "Rau, Block and O'Conner", "11 Bluejay Center");
insert into Publisher (ID, name, address) values (125, "Purdy-Huels", "74 Hovde Hill");
insert into Publisher (ID, name, address) values (126, "Mayert-Trantow", "48 Chinook Circle");
insert into Publisher (ID, name, address) values (127, "Labadie-Wisoky", "797 Moland Drive");
insert into Publisher (ID, name, address) values (128, "Hahn-Dickens", "50 Eagan Terrace");
insert into Publisher (ID, name, address) values (129, "West-Kuhic", "70246 Cascade Hill");
insert into Publisher (ID, name, address) values (130, "Abshire, Jacobson and Runolfsson", "21578 Express Alley");
insert into Publisher (ID, name, address) values (131, "Mohr LLC", "977 Mockingbird Plaza");
insert into Publisher (ID, name, address) values (132, "Adams, Jacobs and Strosin", "08 Division Pass");
insert into Publisher (ID, name, address) values (133, "Prosacco-Kihn", "26331 Judy Terrace");
insert into Publisher (ID, name, address) values (134, "Turner, Lang and Koelpin", "873 Delaware Point");
insert into Publisher (ID, name, address) values (135, "Watsica, Wisozk and Wolff", "3417 Vidon Point");
insert into Publisher (ID, name, address) values (136, "Bosco LLC", "44075 Green Ridge Road");
insert into Publisher (ID, name, address) values (137, "Hayes Group", "63 Hazelcrest Center");
insert into Publisher (ID, name, address) values (138, "Bosco LLC", "06 Gina Junction");
insert into Publisher (ID, name, address) values (139, "Ferry LLC", "2 Straubel Circle");
insert into Publisher (ID, name, address) values (140, "O'Keefe LLC", "5 Parkside Trail");
insert into Publisher (ID, name, address) values (141, "Hessel Inc", "378 Kings Hill");
insert into Publisher (ID, name, address) values (142, "Abshire LLC", "32 Schmedeman Terrace");
insert into Publisher (ID, name, address) values (143, "Hessel LLC", "980 Lerdahl Drive");
insert into Publisher (ID, name, address) values (144, "Jacobi, Tremblay and Crooks", "9 Calypso Plaza");
insert into Publisher (ID, name, address) values (145, "Jacobs Group", "980 Lerdahl Drive");
insert into Publisher (ID, name, address) values (146, "Ziemann-Moen", "48 Chinook Circle");
insert into Publisher (ID, name, address) values (147, "DuBuque LLC", "5985 Monterey Place");
insert into Publisher (ID, name, address) values (148, "Oberbrunner, Kessler and Gorczany", "6 Stephen Pass");
insert into Publisher (ID, name, address) values (149, "Vandervort LLC", "4 Towne Drive");
insert into Publisher (ID, name, address) values (150, "Ziemann-Moen", "09 Thierer Drive");
insert into Publisher (ID, name, address) values (151, "Ritchie, Pouros and Botsford", "47 Mitchell Pass");
insert into Publisher (ID, name, address) values (152, "Heller Group", "9 Calypso Plaza");
insert into Publisher (ID, name, address) values (153, "DuBuque LLC", "5985 Monterey Place");
insert into Publisher (ID, name, address) values (154, "Lind, Fadel and Kuhlman", "326 Golden Leaf Drive");
insert into Publisher (ID, name, address) values (155, "Kautzer LLC", "018 Fulton Alley");
insert into Publisher (ID, name, address) values (156, "Bosco LLC", "640 Parkside Trail");
insert into Publisher (ID, name, address) values (157, "Jacobs Group", "35 Muir Circle");
insert into Publisher (ID, name, address) values (158, "Hettinger-Gaylord", "3417 Vidon Point");
insert into Publisher (ID, name, address) values (159, "Lowe, Ebert and Rath", "3977 Stang Pass");
insert into Publisher (ID, name, address) values (160, "Boyle-Little", "56366 Service Street");
insert into Publisher (ID, name, address) values (161, "Gibson, Langworth and McDermott", "209 Old Shore Plaza");
insert into Publisher (ID, name, address) values (162, "Ritchie LLC", "94 Division Crossing");
insert into Publisher (ID, name, address) values (163, "Crooks LLC", "5795 Westport Parkway");
insert into Publisher (ID, name, address) values (164, "West-Kuhic", "56 Springview Junction");
insert into Publisher (ID, name, address) values (165, "Rath Group", "56 Troy Parkway");
insert into Publisher (ID, name, address) values (166, "Hessel LLC", "66 Upham Lane");
insert into Publisher (ID, name, address) values (167, "Cronin-Ratke", "66 Upham Lane");
insert into Publisher (ID, name, address) values (168, "Thiel and Sons", "65786 Gulseth Road");
insert into Publisher (ID, name, address) values (169, "Wilkinson, Wuckert and Franecki", "2689 Hoepker Point");
insert into Publisher (ID, name, address) values (170, "Deckow, Skiles and Terry", "5 Cardinal Junction");
insert into Publisher (ID, name, address) values (171, "Hane-Metz", "873 Delaware Point");
insert into Publisher (ID, name, address) values (172, "Lindgren and Sons", "70246 Cascade Hill");
insert into Publisher (ID, name, address) values (173, "Bogan, Auer and Crooks", "66 Claremont Pass");
insert into Publisher (ID, name, address) values (174, "Schaefer, Wuckert and Kihn", "7 Troy Parkway");
insert into Publisher (ID, name, address) values (175, "Boyle-Little", "88582 Cottonwood Point");
insert into Publisher (ID, name, address) values (176, "Graham-Brown", "786 Garrison Junction");
insert into Publisher (ID, name, address) values (177, "Emmerich, Kilback and Bednar", "17 Nancy Park");
insert into Publisher (ID, name, address) values (178, "Flatley-Weber", "6 New Castle Road");
insert into Publisher (ID, name, address) values (179, "Hane-Metz", "11776 Arrowood Trail");
insert into Publisher (ID, name, address) values (180, "Harber Inc", "06144 Independence Alley");
insert into Publisher (ID, name, address) values (181, "Hermiston-Goodwin", "56366 Service Street");
insert into Publisher (ID, name, address) values (182, "Lowe, Ebert and Rath", "06144 Independence Alley");
insert into Publisher (ID, name, address) values (183, "Lindgren and Sons", "65320 Moose Avenue");
insert into Publisher (ID, name, address) values (184, "Ferry LLC", "62544 Eastwood Circle");
insert into Publisher (ID, name, address) values (185, "Harber Inc", "326 Golden Leaf Drive");
insert into Publisher (ID, name, address) values (186, "Reinger-Kassulke", "5795 Westport Parkway");
insert into Publisher (ID, name, address) values (187, "Crooks LLC", "3157 Mendota Way");
insert into Publisher (ID, name, address) values (188, "Mohr LLC", "46727 Park Meadow Alley");
insert into Publisher (ID, name, address) values (189, "McGlynn and Sons", "43 Meadow Vale Park");
insert into Publisher (ID, name, address) values (190, "Crona-Schimmel", "242 Debra Crossing");
insert into Publisher (ID, name, address) values (191, "Ziemann-Moen", "56 Springview Junction");
insert into Publisher (ID, name, address) values (192, "Kautzer LLC", "35 Jana Point");
insert into Publisher (ID, name, address) values (193, "Haag-Wisoky", "56366 Service Street");
insert into Publisher (ID, name, address) values (194, "Gutkowski, Rice and Abshire", "6 Stephen Pass");
insert into Publisher (ID, name, address) values (195, "Hackett LLC", "46 Emmet Center");
insert into Publisher (ID, name, address) values (196, "Stiedemann Group", "018 Fulton Alley");
insert into Publisher (ID, name, address) values (197, "Oberbrunner, Kessler and Gorczany", "9 Calypso Plaza");
insert into Publisher (ID, name, address) values (198, "Rosenbaum, Botsford and Smitham", "63 Hazelcrest Center");
insert into Publisher (ID, name, address) values (199, "Blick, Haley and Rohan", "5 Weeping Birch Avenue");
insert into Publisher (ID, name, address) values (200, "Gislason, Harris and Altenwerth", "9 Northport Junction");
