insert into Tag (name) values ('Fantasy');
insert into Tag (name) values ('Adventure');
insert into Tag (name) values ('Romance');
insert into Tag (name) values ('Contemporary');
insert into Tag (name) values ('Dystopian');
insert into Tag (name) values ('Mystery');
insert into Tag (name) values ('Horror');
insert into Tag (name) values ('Thriller');
insert into Tag (name) values ('Paranormal');
insert into Tag (name) values ('Historical fiction');
insert into Tag (name) values ('Science Fiction');
insert into Tag (name) values ('Children');
insert into Tag (name) values ('Memoir');
insert into Tag (name) values ('Cookbook');
insert into Tag (name) values ('Art');
insert into Tag (name) values ('Self-help');
insert into Tag (name) values ('Development');
insert into Tag (name) values ('Motivational');
insert into Tag (name) values ('Health');
insert into Tag (name) values ('History');
insert into Tag (name) values ('Travel');
insert into Tag (name) values ('Families & Relationships');
insert into Tag (name) values ('Humor');