INSERT INTO Tag (name) VALUES
('Romance'),
('Mystery'),
('Science Fiction'),
('Fantasy'),
('Historical Fiction'),
('Horror'),
('Thriller'),
('Crime'),
('Adventure'),
('Comedy'),
('Drama'),
('Action'),
('Children''s'),
('Young Adult'),
('Science'),
('Biography'),
('Autobiography'),
('Memoir'),
('Travel'),
('Self-Help'),
('Health'),
('Cooking'),
('Business'),
('History'),
('Art'),
('Music'),
('Philosophy'),
('Religion'),
('Psychology'),
('Sociology'),
('True Crime'),
('Western'),
('Erotica'),
('Humor'),
('Politics'),
('Sports'),
('Nature'),
('Education'),
('Technology'),
('Fairy Tale');
